# Generated by Django 5.0.7 on 2024-08-03 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IDProd", models.IntegerField()),
                ("Cod", models.CharField(max_length=244)),
                ("Desc", models.CharField(max_length=244)),
                ("Cod_Barra", models.CharField(max_length=299)),
                ("Status", models.IntegerField()),
                ("Date_Create", models.DateTimeField(auto_now_add=True)),
                ("Unit_Cost", models.FloatField()),
                ("Sale_Price", models.FloatField()),
            ],
        ),
    ]
